/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        //TODO: make this test pass by making it test functions in class ArrayListOfName
        assertNotNull(null, "app should have a greeting");
    }
}
